#!/usr/bin/env node
/**
 * Bridge between the two variants.
 *
 * Opens a real browser, records every XHR/fetch the wizard makes while you walk
 * it by hand, and — when you press ENTER on the date step — writes a ready
 * .env.captured with the request that fetched the dates, its cookies and its
 * headers. Copy that over .env and Variant 1 is configured.
 *
 * Beats hand-editing "Copy as cURL", and it also shows you what the page is
 * actually calling, which is what you need to pick TRIGGER_SELECTOR later.
 */
import readline from 'node:readline/promises';
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';

import { str, num, bool, list } from './src/config.js';
import { normalize } from './src/detect.js';

const config = {
  startUrl: str('START_URL', 'https://pes.minv.sk/'),
  executablePath: str('CHROMIUM_EXECUTABLE_PATH'),
  headless: bool('HEADLESS', false),
  outDir: str('CAPTURE_DIR', 'captured'),
  maxBodyChars: num('CAPTURE_MAX_BODY', 20_000),
  noSlotsPhrases: list('NO_SLOTS_TEXT', ['Nie sú momentálne dostupné žiadne termíny']),
};

/** Words that suggest "this is the request that lists appointments". */
const INTERESTING = ['termin', 'termín', 'date', 'datum', 'dátum', 'slot', 'availab', 'volny', 'voľn', 'cas', 'čas'];

const captured = [];

function scoreRequest(entry) {
  let score = 0;
  const url = normalize(entry.url);
  const body = normalize(entry.responseBody ?? '');

  if (entry.resourceType === 'xhr' || entry.resourceType === 'fetch') score += 5;
  // The wizard page itself always mentions "termín" — it is never the endpoint.
  if (entry.resourceType === 'document') score -= 6;
  if ((entry.responseContentType ?? '').includes('json')) score += 4;
  for (const word of INTERESTING) {
    if (url.includes(normalize(word))) score += 3;
    if (body.includes(normalize(word))) score += 1;
  }
  for (const phrase of config.noSlotsPhrases) {
    if (body.includes(normalize(phrase))) score += 8; // this endpoint reports slot state
  }
  if (/\d{4}-\d{2}-\d{2}|\d{2}\.\d{2}\.\d{4}/.test(entry.responseBody ?? '')) score += 4;
  return score;
}

/**
 * dotenv strips surrounding quotes but does NOT unescape \" or \' inside them,
 * so an escaped quote would survive into the value and break JSON.parse.
 * Pick a quote character the value does not contain instead.
 */
function envLine(key, value) {
  if (value === undefined || value === null || value === '') return `# ${key}=`;
  const flat = String(value).replace(/[\r\n]+/g, ' ');

  if (!flat.includes("'")) return `${key}='${flat}'`;
  if (!flat.includes('"')) return `${key}="${flat}"`;
  return `# FIXME: value contains both quote types, quote it by hand\n# ${key}=${flat}`;
}

/** page.url() is "about:blank" for the very first request — useless as a Referer. */
function usablePageUrl(entry) {
  if (entry.pageUrl && entry.pageUrl !== 'about:blank') return entry.pageUrl;
  return new URL(entry.url).origin;
}

async function writeEnvTemplate(best, cookieHeader, userAgent) {
  const headers = best.requestHeaders ?? {};
  const csrfEntry = Object.entries(headers).find(([name]) =>
    /csrf|xsrf|verification.?token/i.test(name),
  );

  const skipHeaders = new Set([
    'cookie', 'user-agent', 'accept', 'accept-language', 'accept-encoding',
    'content-type', 'content-length', 'referer', 'origin', 'host', 'connection',
    'x-requested-with', 'cache-control', 'pragma',
  ]);
  const extra = Object.fromEntries(
    Object.entries(headers).filter(
      ([name]) =>
        !skipHeaders.has(name.toLowerCase()) &&
        !name.startsWith(':') &&
        !name.toLowerCase().startsWith('sec-') &&
        (!csrfEntry || name !== csrfEntry[0]),
    ),
  );

  // A body with both quote characters in it cannot be inlined into .env, so it
  // goes to a file and monitor.js reads it from there.
  const body = best.postData ?? '';
  let bodyLine = envLine('REQUEST_BODY', body);
  if (body && bodyLine.startsWith('#')) {
    const bodyPath = path.join(config.outDir, 'request-body.txt');
    await fs.writeFile(bodyPath, body, 'utf8');
    bodyLine = `${envLine('REQUEST_BODY_FILE', bodyPath)}  # body had both quote types`;
  }

  const lines = [
    '# Generated by capture-session.js — review, then: cp .env.captured .env',
    `# captured at ${new Date().toISOString()}`,
    '# NOTE: cookies expire. Re-capture whenever monitor.js reports 401/403.',
    '',
    envLine('TARGET_URL', best.url),
    envLine('METHOD', best.method),
    envLine('COOKIE_HEADER', cookieHeader),
    envLine('CSRF_HEADER_NAME', csrfEntry ? csrfEntry[0] : 'X-CSRF-TOKEN'),
    envLine('CSRF_TOKEN', csrfEntry ? csrfEntry[1] : ''),
    bodyLine,
    envLine('CONTENT_TYPE', headers['content-type'] ?? 'application/json'),
    envLine('REFERER', headers.referer ?? usablePageUrl(best)),
    envLine('ORIGIN', headers.origin ?? new URL(best.url).origin),
    envLine('USER_AGENT', userAgent),
    envLine('EXTRA_HEADERS', Object.keys(extra).length ? JSON.stringify(extra) : ''),
    '',
    envLine('INTERVAL_MS', '15000'),
    envLine('NO_SLOTS_TEXT', config.noSlotsPhrases.join(',')),
    '# SLOT_JSON_PATH=data.terms',
    '',
    '# TELEGRAM_BOT_TOKEN=',
    '# TELEGRAM_CHAT_ID=',
    '',
  ];

  const target = '.env.captured';
  await fs.writeFile(target, lines.join('\n'), 'utf8');
  return target;
}

async function main() {
  await fs.mkdir(config.outDir, { recursive: true });
  const logPath = path.join(config.outDir, 'requests.jsonl');
  const log = await fs.open(logPath, 'w');

  const browser = await chromium.launch({
    headless: config.headless,
    executablePath: config.executablePath || undefined,
    args: ['--disable-blink-features=AutomationControlled'],
  });
  const context = await browser.newContext({ viewport: null, locale: 'sk-SK' });
  const page = await context.newPage();

  page.on('response', async (response) => {
    const request = response.request();
    const type = request.resourceType();
    if (!['xhr', 'fetch', 'document'].includes(type)) return;

    const entry = {
      at: new Date().toISOString(),
      resourceType: type,
      method: request.method(),
      url: response.url(),
      status: response.status(),
      pageUrl: page.url(),
      requestHeaders: await request.allHeaders().catch(() => ({})),
      responseContentType: response.headers()['content-type'] ?? '',
      postData: request.postData() ?? '',
      responseBody: '',
    };

    try {
      entry.responseBody = (await response.text()).slice(0, config.maxBodyChars);
    } catch {
      // body not retained — keep the metadata anyway
    }

    captured.push(entry);
    await log.write(`${JSON.stringify(entry)}\n`);
    console.log(`  [${entry.status}] ${entry.method} ${entry.url.slice(0, 120)}`);
  });

  console.log('Session capture — walk the wizard by hand, everything is recorded.\n');
  await page.goto(config.startUrl, { waitUntil: 'domcontentloaded' });

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  await rl.question(
    '\n>>> Solve the CAPTCHA, enter the SMS code, get to the date-selection step.\n' +
      '>>> Then press ENTER here to dump the session.\n',
  );
  rl.close();

  const cookies = await context.cookies();
  const cookieHeader = cookies.map((c) => `${c.name}=${c.value}`).join('; ');
  const userAgent = await page.evaluate(() => navigator.userAgent);

  const ranked = captured
    .map((entry) => ({ entry, score: scoreRequest(entry) }))
    .sort((a, b) => b.score - a.score || b.entry.at.localeCompare(a.entry.at));

  console.log('\nTop candidates for TARGET_URL:');
  for (const { entry, score } of ranked.slice(0, 8)) {
    console.log(`  score ${String(score).padStart(3)}  ${entry.method} ${entry.url.slice(0, 110)}`);
  }

  if (ranked.length === 0) {
    console.error('\nNothing captured — did the wizard actually load?');
  } else {
    const target = await writeEnvTemplate(ranked[0].entry, cookieHeader, userAgent);
    console.log(`\nWrote ${target} (top candidate).`);
    console.log(`Full request log: ${logPath}`);
    console.log('If the top candidate is wrong, pick another URL from the log and edit TARGET_URL by hand.');
    console.log('\nNext: cp .env.captured .env && npm run monitor');
    console.log('Do it quickly — the cookies are already ticking.');
  }

  await log.close();
  await browser.close();
}

main().catch((err) => {
  console.error(`\nFatal: ${err.stack ?? err.message}`);
  process.exit(1);
});
